name: Build

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'latest/**'
      - 'legacy/**'
      - .github/workflows/build.yml
      - versions.json
  workflow_dispatch:

env:
  DOCKERHUB_REPOSITORY: ${{ github.repository_owner }}/imagemagick
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.latest }}
      legacy: ${{ steps.set-matrix.outputs.legacy }}
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Set matrix
        id: set-matrix
        run: |
          json="$(cat ./versions.json)"
          {
            echo "latest=$(jq -cM .latest <<< "$json")"
            echo "legacy=$(jq -cM .legacy <<< "$json")"
          } >> "$GITHUB_OUTPUT"

  legacy-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.legacy) }}
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to private registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Build a Debian image
        uses: docker/build-push-action@v7
        id: debian
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-legacy-${{ matrix.image.version }}-debian
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-legacy-${{ matrix.image.version }}-debian,mode=max
          context: .
          file: ./legacy/debian/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:legacy-${{ matrix.image.version }}-debian
      - name: Build an Alpine image
        uses: docker/build-push-action@v7
        id: alpine
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-legacy-${{ matrix.image.version }}-alpine
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-legacy-${{ matrix.image.version }}-alpine,mode=max
          context: .
          file: ./legacy/alpine/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:legacy-${{ matrix.image.version }}-alpine
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  latest-build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.latest) }}
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to private registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Build a Debian image
        uses: docker/build-push-action@v7
        id: debian
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-${{ matrix.image.version }}-debian
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-${{ matrix.image.version }}-debian,mode=max
          context: .
          file: ./latest/debian/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:${{ matrix.image.version }}-debian
      - name: Build an Alpine image
        uses: docker/build-push-action@v7
        id: alpine
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-${{ matrix.image.version }}-alpine
          cache-to: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-${{ matrix.image.version }}-alpine,mode=max
          context: .
          file: ./latest/alpine/Dockerfile
          labels: maintainer=victor@popkov.me
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: |
            ${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:${{ matrix.image.version }}-alpine
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  legacy-push:
    needs: [prepare, legacy-build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.legacy) }}
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to private registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare Docker meta for a Debian image
        uses: docker/metadata-action@v6
        id: debian-meta
        with:
          flavor: prefix=legacy-,onlatest=true
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-debian
            ${{ matrix.image.latest && 'type=raw,value=debian' || '' }}
      - name: Build a Debian image
        uses: docker/build-push-action@v7
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-legacy-${{ matrix.image.version }}-debian
          context: .
          file: ./legacy/debian/Dockerfile
          labels: ${{ steps.debian-meta.outputs.labels }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.debian-meta.outputs.tags }}
      - name: Prepare Docker meta for an Alpine image
        uses: docker/metadata-action@v6
        id: alpine-meta
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          flavor: |
            latest=${{ matrix.image.latest || 'false' }}
            prefix=legacy-,onlatest=true
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-alpine
            type=raw,value=${{ matrix.image.version }}
            ${{ matrix.image.latest && 'type=raw,value=alpine' || '' }}
            ${{ matrix.image.latest && 'type=raw,prefix=,value=legacy' || '' }}
      - name: Build an Alpine image
        uses: docker/build-push-action@v7
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-legacy-${{ matrix.image.version }}-alpine
          context: .
          file: ./legacy/alpine/Dockerfile
          labels: ${{ steps.alpine-meta.outputs.labels }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.alpine-meta.outputs.tags }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  latest-push:
    needs: [prepare, latest-build, legacy-push]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.latest) }}
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:qemu-v10.2.3-68
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to private registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare Docker meta for a Debian image
        uses: docker/metadata-action@v6
        id: debian-meta
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-debian
            ${{ matrix.image.latest && 'type=raw,value=debian' || '' }}
      - name: Build a Debian image
        uses: docker/build-push-action@v7
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-${{ matrix.image.version }}-debian
          context: .
          file: ./latest/debian/Dockerfile
          labels: ${{ steps.debian-meta.outputs.labels }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.debian-meta.outputs.tags }}
      - name: Prepare Docker meta for an Alpine image
        uses: docker/metadata-action@v6
        id: alpine-meta
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ghcr.io/${{ env.DOCKERHUB_REPOSITORY }}
          flavor: latest=${{ matrix.image.latest || 'false' }}
          labels: maintainer=victor@popkov.me
          tags: |
            type=raw,value=${{ matrix.image.version }}-alpine
            type=raw,value=${{ matrix.image.version }}
            ${{ matrix.image.latest && 'type=raw,value=alpine' || '' }}
      - name: Build an Alpine image
        uses: docker/build-push-action@v7
        with:
          build-args: IMAGEMAGICK_VERSION=${{ matrix.image.version }}
          cache-from: type=registry,ref=${{ secrets.PRIVATE_REGISTRY_HOST }}/imagemagick:cache-${{ matrix.image.version }}-alpine
          context: .
          file: ./latest/alpine/Dockerfile
          labels: ${{ steps.alpine-meta.outputs.labels }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          provenance: false
          pull: true
          push: ${{ !env.ACT }}
          sbom: false
          tags: ${{ steps.alpine-meta.outputs.tags }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            ImageMagick version: ${{ matrix.image.version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
